version: '3.8'

services:
  memory-game:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_production_jwt_secret_here
    volumes:
      - ./database:/app/database
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - memory-game
    restart: unless-stopped